export enum EXCEPTION_CODE {
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_SCHEMA = 'INVALID_SCHEMA',
  FORBBIDEN = 'FORBBIDEN',
  UNKNOWN = 'UNKNOWN',
  DATABASE = 'DATABASE',
  NOT_FOUND = 'NOT_FOUND',
  DEPRECATED = 'DEPRECATED',
  REDIS = 'REDIS',
}
